# Generated by Django 2.2.5 on 2022-06-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tessy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
